# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  default_map_bounds:
    from: [64.09140752262307, 83.6953125]
    to:   [1.792253570362446, -143.3984375]

development:
  <<: *default
  secret_key_base: 5e96ca1fb920a938789cea5b1970901e3a7db2da1bc32dd2d307de80719833c9394d8e8827f78d889e9c3313fc9d1c56a42287a5351fa063b7ba4753bda3380d

test:
  <<: *default
  secret_key_base: a927fd81f46248ce509021de8eef69115abcb66e53ead71053eff115e904d9b4f33b65db0254dab367e93ed4f56ae1dd26716789cb31a0823fad4938d12c687c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
